### PR TITLE
Fix #161 use clangd instead

### LINKED ISSUE #161: Switch from cquery to clangd as a default C/C++ language server
# cquery
- not maintained for over a year
- not available in any package manager
- not even binary releases available, huge hassle to install

# clangd
- part of LLVM/Clang suite, many C++ developers have already installed
- multiplatform
- easily installed through package managers by a single command
- actively developed

# Proposed change

Change the default language server to clangd. It works out of the box like this:

```ini
[language.cpp]
command = "clangd"
args = []
```

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by JanPokorny** [comment]
@zxqfl Please merge this, there is really no reason to continue using `cquery`.

**Comment by MTCoster** [comment]
If there's anything holding up this PR, I'd be happy to help it along! This is a much needed modernisation.

**Comment by JanPokorny** [comment]
@MTCoster I'm afraid that the only dev of TabNine, @zxqfl, is not very active and often disappears for months -- see https://github.com/zxqfl/TabNine/issues/179#issuecomment-546889432. Even though TabNine works quite well, it should be considered a dead project.

You can apply the change in this PR locally, though.

**Comment by drorweiss** [comment]
Thank you for submitting this PR. TabNine isn't a dead project, it's in transition; Starting January 2020, the Codota team, together with @zxqfl, will be maintaining and improving TabNine to make sure this amazing project remains worthy of your trust. We're catching up on issues and will update about this PR as well, shortly. Thanks for your insistence and your patience.
--Dror Weiss (CEO @codota)

**Comment by JanPokorny** [comment]
@drorweiss Glad to hear that! Is there some official announcement? Last entry on the official blog is from August.

**Comment by drorweiss** [comment]
@JanPokorny We'll issue a formal communication in TabNine and Codota blog - expected next week.

**Comment by Shougo** [comment]
Thank you!

**Comment by JanPokorny** [comment]
@drorweiss Hello, when exactly is "next week" coming up? I see nothing here https://tabnine.com/blog/

**Pull request merged**
